# Generated by Django 6.0.6 on 2026-09-25 04:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{3,20}$', 'Use 3–20 letters and digits, no spaces or symbols.')])),
                ('percent_off', models.PositiveSmallIntegerField(help_text='A whole number from 1 to 90.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='percent off')),
                ('expires_on', models.DateField(blank=True, help_text='Valid through the end of this day. Leave empty to never expire.', null=True, verbose_name='expires on')),
                ('retired_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('products', models.ManyToManyField(blank=True, help_text='Leave empty to apply to the whole order.', related_name='coupons', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('percent_off__gte', 1), ('percent_off__lte', 90)), name='coupon_percent_off_1_to_90')],
            },
        ),
    ]
