# Generated by Django 6.0.6 on 2026-10-04 19:11

import products.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=products.images.ProductImageField(blank=True, help_text='Optional. A JPEG, PNG, or WebP image, up to 5 MB and at least 600 pixels on its shortest side.', max_length=255, upload_to='products/', validators=[products.images.validate_product_image]),
        ),
    ]
